/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2020 Jerzy Kasenbreg
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 */

#ifndef USB_DESCRIPTORS_H_
#define USB_DESCRIPTORS_H_

enum
{
    // UAC2 Audio Function (AC + 2x AS)
    ITF_NUM_AUDIO_CONTROL = 0,
    ITF_NUM_AUDIO_STREAMING_STEREO_OUT,
    ITF_NUM_AUDIO_STREAMING_STEREO_IN,

// USB-MIDI (Audio Class, MIDIStreaming). TinyUSB MIDI uses 2 interfaces.
#if 1  // CFG_TUD_MIDI
    ITF_NUM_MIDI,
    ITF_NUM_MIDI_STREAMING,
#endif

    ITF_NUM_TOTAL
};

// Number of interfaces that belong to the UAC2 Audio Function above (IAD scope)
#define ITF_NUM_AUDIO_FUNC_1_N_ITF 3

//--------------------------------------------------------------------+
// UAC2 DESCRIPTOR TEMPLATES
//--------------------------------------------------------------------+

// Unit numbers are arbitrary selected
#define UAC2_ENTITY_CLOCK 0x04
// Speaker path
#define UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL  0x01
#define UAC2_ENTITY_STEREO_OUT_FEATURE_UNIT    0x02
#define UAC2_ENTITY_STEREO_OUT_OUTPUT_TERMINAL 0x03
// Microphone path
#define UAC2_ENTITY_STEREO_IN_INPUT_TERMINAL  0x11
#define UAC2_ENTITY_STEREO_IN_OUTPUT_TERMINAL 0x13

// Simplified: Only 1 alternate setting (24bit) per interface
#define TUD_AUDIO20_AUDIOIF_STEREO_DESC_LEN (TUD_AUDIO20_DESC_IAD_LEN + TUD_AUDIO20_DESC_STD_AC_LEN + TUD_AUDIO20_DESC_CS_AC_LEN + TUD_AUDIO20_DESC_CLK_SRC_LEN + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_FEATURE_UNIT_LEN(4) + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN + TUD_AUDIO20_DESC_STD_AC_INT_EP_LEN /* Interface 1, Alternate 0 */ \
                                             + TUD_AUDIO20_DESC_STD_AS_LEN                                                                                                                                                                                                                                                                                                            /* Interface 1, Alternate 1 (24bit) */ \
                                             + TUD_AUDIO20_DESC_STD_AS_LEN + TUD_AUDIO20_DESC_CS_AS_INT_LEN + TUD_AUDIO20_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO20_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO20_DESC_CS_AS_ISO_EP_LEN + TUD_AUDIO20_DESC_STD_AS_ISO_FB_EP_LEN                                                                                                                              /* Interface 2, Alternate 0 */ \
                                             + TUD_AUDIO20_DESC_STD_AS_LEN                                                                                                                                                                                                                                                                                                            /* Interface 2, Alternate 1 (24bit) */ \
                                             + TUD_AUDIO20_DESC_STD_AS_LEN + TUD_AUDIO20_DESC_CS_AS_INT_LEN + TUD_AUDIO20_DESC_TYPE_I_FORMAT_LEN + TUD_AUDIO20_DESC_STD_AS_ISO_EP_LEN + TUD_AUDIO20_DESC_CS_AS_ISO_EP_LEN)

#define TUD_AUDIO20_AUDIOIF_STEREO_DESCRIPTOR(_stridx_out, _stridx_in, _epout, _epin, _epfb, _epint)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           \
    /* Standard Interface Association Descriptor (IAD) */                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      \
    TUD_AUDIO20_DESC_IAD(/*_firstitf*/ ITF_NUM_AUDIO_CONTROL, /*_nitfs*/ ITF_NUM_AUDIO_FUNC_1_N_ITF, /*_stridx*/ 0x00),                                                                                                                                                                                                                                                                                                                                                                                                                                           /* Standard AC Interface Descriptor(4.7.1) */                                \
        TUD_AUDIO20_DESC_STD_AC(/*_itfnum*/ ITF_NUM_AUDIO_CONTROL, /*_nEPs*/ 0x01, /*_stridx*/ 0x00),                                                                                                                                                                                                                                                                                                                                                                                                                                                             /* Class-Specific AC Interface Header Descriptor(4.7.2) */                   \
        TUD_AUDIO20_DESC_CS_AC(/*_bcdADC*/ 0x0200, /*_category*/ AUDIO20_FUNC_MUSICAL_INSTRUMENT, /*_totallen*/ TUD_AUDIO20_DESC_CLK_SRC_LEN + TUD_AUDIO20_DESC_FEATURE_UNIT_LEN(4) + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN + TUD_AUDIO20_DESC_INPUT_TERM_LEN + TUD_AUDIO20_DESC_OUTPUT_TERM_LEN, /*_ctrl*/ AUDIO20_CS_AS_INTERFACE_CTRL_LATENCY_POS),                                                                                                                                                                               /* Clock Source Descriptor(4.7.2.1) */                                       \
        TUD_AUDIO20_DESC_CLK_SRC(/*_clkid*/ UAC2_ENTITY_CLOCK, /*_attr*/ 3, /*_ctrl*/ 7, /*_assocTerm*/ 0x00, /*_stridx*/ 0x00),                                                                                                                                                                                                                                                                                                                                                                                                                                  /* Input Terminal Descriptor(4.7.2.4) */                                     \
        TUD_AUDIO20_DESC_INPUT_TERM(/*_termid*/ UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL, /*_termtype*/ AUDIO_TERM_TYPE_USB_STREAMING, /*_assocTerm*/ UAC2_ENTITY_STEREO_IN_OUTPUT_TERMINAL, /*_clkid*/ UAC2_ENTITY_CLOCK, /*_nchannelslogical*/ 0x04, /*_channelcfg*/ AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, /*_idxchannelnames*/ 0x00, /*_ctrl*/ 0 * (AUDIO20_CTRL_R << AUDIO20_IN_TERM_CTRL_CONNECTOR_POS), /*_stridx*/ 0x00),                                                                                                                                    /* Feature Unit Descriptor(4.7.2.8) */                                       \
        TUD_AUDIO20_DESC_FEATURE_UNIT(/*_unitid*/ UAC2_ENTITY_STEREO_OUT_FEATURE_UNIT, /*_srcid*/ UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL, /*_stridx*/ 0x00, /*_ctrlch0master*/ (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), /*_ctrlch1*/ (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), /*_ctrlch2*/ (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), /*_ctrlch3*/ (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS), /*_ctrlch4*/ (AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_MUTE_POS | AUDIO20_CTRL_RW << AUDIO20_FEATURE_UNIT_CTRL_VOLUME_POS)), /* Output Terminal Descriptor(4.7.2.5) */                                    \
        TUD_AUDIO20_DESC_OUTPUT_TERM(/*_termid*/ UAC2_ENTITY_STEREO_OUT_OUTPUT_TERMINAL, /*_termtype*/ AUDIO_TERM_TYPE_OUT_GENERIC_SPEAKER, /*_assocTerm*/ 0x00, /*_srcid*/ UAC2_ENTITY_STEREO_OUT_FEATURE_UNIT, /*_clkid*/ UAC2_ENTITY_CLOCK, /*_ctrl*/ 0x0000, /*_stridx*/ 0x00),                                                                                                                                                                                                                                                                               /* Input Terminal Descriptor(4.7.2.4) */                                     \
        TUD_AUDIO20_DESC_INPUT_TERM(/*_termid*/ UAC2_ENTITY_STEREO_IN_INPUT_TERMINAL, /*_termtype*/ AUDIO_TERM_TYPE_IN_GENERIC_MIC, /*_assocTerm*/ 0x00, /*_clkid*/ UAC2_ENTITY_CLOCK, /*_nchannelslogical*/ 0x04, /*_channelcfg*/ AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, /*_idxchannelnames*/ 0x00, /*_ctrl*/ 0 * (AUDIO20_CTRL_R << AUDIO20_IN_TERM_CTRL_CONNECTOR_POS), /*_stridx*/ 0x00),                                                                                                                                                                     /* Output Terminal Descriptor(4.7.2.5) */                                    \
        TUD_AUDIO20_DESC_OUTPUT_TERM(/*_termid*/ UAC2_ENTITY_STEREO_IN_OUTPUT_TERMINAL, /*_termtype*/ AUDIO_TERM_TYPE_USB_STREAMING, /*_assocTerm*/ UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL, /*_srcid*/ UAC2_ENTITY_STEREO_IN_INPUT_TERMINAL, /*_clkid*/ UAC2_ENTITY_CLOCK, /*_ctrl*/ 0x0000, /*_stridx*/ 0x00),                                                                                                                                                                                                                                                    /* Standard AC Interrupt Endpoint Descriptor(4.8.2.1) */                     \
        TUD_AUDIO20_DESC_STD_AC_INT_EP(/*_ep*/ _epint, /*_interval*/ 0x01), /* Standard AS Interface Descriptor(4.9.1) */                                                                                                                                                                                                                                                                                                                                                                                                                                         /* Interface 1, Alternate 0 - default alternate setting with 0 bandwidth */  \
        TUD_AUDIO20_DESC_STD_AS_INT(/*_itfnum*/ (uint8_t) (ITF_NUM_AUDIO_STREAMING_STEREO_OUT), /*_altset*/ 0x00, /*_nEPs*/ 0x00, /*_stridx*/ _stridx_out), /* Standard AS Interface Descriptor(4.9.1) */                                                                                                                                                                                                                                                                                                                                                         /* Interface 1, Alternate 1 - 24bit data streaming */                        \
        TUD_AUDIO20_DESC_STD_AS_INT(/*_itfnum*/ (uint8_t) (ITF_NUM_AUDIO_STREAMING_STEREO_OUT), /*_altset*/ 0x01, /*_nEPs*/ 0x02, /*_stridx*/ _stridx_out),                                                                                                                                                                                                                                                                                                                                                                                                       /* Class-Specific AS Interface Descriptor(4.9.2) */                          \
        TUD_AUDIO20_DESC_CS_AS_INT(/*_termid*/ UAC2_ENTITY_STEREO_OUT_INPUT_TERMINAL, /*_ctrl*/ AUDIO20_CTRL_NONE, /*_formattype*/ AUDIO20_FORMAT_TYPE_I, /*_formats*/ AUDIO20_DATA_FORMAT_TYPE_I_PCM, /*_nchannelsphysical*/ CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX, /*_channelcfg*/ AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, /*_stridx*/ 0x00),                                                                                                                                                                                                                       /* Type I Format Type Descriptor(2.3.1.6 - Audio Formats) */                 \
        TUD_AUDIO20_DESC_TYPE_I_FORMAT(CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_RX),                                                                                                                                                                                                                                                                                                                                                                                                                         /* Standard AS Isochronous Audio Data Endpoint Descriptor(4.10.1.1) */       \
        TUD_AUDIO20_DESC_STD_AS_ISO_EP(/*_ep*/ _epout, /*_attr*/ (uint8_t) ((uint8_t) TUSB_XFER_ISOCHRONOUS | (uint8_t) TUSB_ISO_EP_ATT_ASYNCHRONOUS | (uint8_t) TUSB_ISO_EP_ATT_DATA), /*_maxEPsize*/ TUD_AUDIO_EP_SIZE(TUD_OPT_HIGH_SPEED, CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_RX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_RX), /*_interval*/ 0x01),                                                                                                                                                                 /* Class-Specific AS Isochronous Audio Data Endpoint Descriptor(4.10.1.2) */ \
        TUD_AUDIO20_DESC_CS_AS_ISO_EP(/*_attr*/ AUDIO20_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, /*_ctrl*/ AUDIO20_CTRL_NONE, /*_lockdelayunit*/ AUDIO20_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_MILLISEC, /*_lockdelay*/ 0x0001),                                                                                                                                                                                                                                                                                                                                      /* Standard AS Isochronous Feedback Endpoint Descriptor(4.10.2.1) */          \
        TUD_AUDIO20_DESC_STD_AS_ISO_FB_EP(/*_ep*/ _epfb, /*_epsize*/ 4, /*_interval*/ TUD_OPT_HIGH_SPEED ? 4 : 1), /* Standard AS Interface Descriptor(4.9.1) */                                                                                                                                                                                                                                                                                                                                                     /* Interface 2, Alternate 0 - default alternate setting with 0 bandwidth */  \
        TUD_AUDIO20_DESC_STD_AS_INT(/*_itfnum*/ (uint8_t) (ITF_NUM_AUDIO_STREAMING_STEREO_IN), /*_altset*/ 0x00, /*_nEPs*/ 0x00, /*_stridx*/ _stridx_in), /* Standard AS Interface Descriptor(4.9.1) */                                                                                                                                                                                                                                                                                                                                                           /* Interface 2, Alternate 1 - 24bit data streaming */                        \
        TUD_AUDIO20_DESC_STD_AS_INT(/*_itfnum*/ (uint8_t) (ITF_NUM_AUDIO_STREAMING_STEREO_IN), /*_altset*/ 0x01, /*_nEPs*/ 0x01, /*_stridx*/ _stridx_in),                                                                                                                                                                                                                                                                                                                                                                                                         /* Class-Specific AS Interface Descriptor(4.9.2) */                          \
        TUD_AUDIO20_DESC_CS_AS_INT(/*_termid*/ UAC2_ENTITY_STEREO_IN_OUTPUT_TERMINAL, /*_ctrl*/ AUDIO20_CTRL_NONE, /*_formattype*/ AUDIO20_FORMAT_TYPE_I, /*_formats*/ AUDIO20_DATA_FORMAT_TYPE_I_PCM, /*_nchannelsphysical*/ CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX, /*_channelcfg*/ AUDIO20_CHANNEL_CONFIG_NON_PREDEFINED, /*_stridx*/ 0x00),                                                                                                                                                                                                                       /* Type I Format Type Descriptor(2.3.1.6 - Audio Formats) */                 \
        TUD_AUDIO20_DESC_TYPE_I_FORMAT(CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_RESOLUTION_TX),                                                                                                                                                                                                                                                                                                                                                                                                                         /* Standard AS Isochronous Audio Data Endpoint Descriptor(4.10.1.1) */       \
        TUD_AUDIO20_DESC_STD_AS_ISO_EP(/*_ep*/ _epin, /*_attr*/ (uint8_t) ((uint8_t) TUSB_XFER_ISOCHRONOUS | (uint8_t) TUSB_ISO_EP_ATT_ASYNCHRONOUS | (uint8_t) TUSB_ISO_EP_ATT_DATA), /*_maxEPsize*/ TUD_AUDIO_EP_SIZE(TUD_OPT_HIGH_SPEED, CFG_TUD_AUDIO_FUNC_1_MAX_SAMPLE_RATE, CFG_TUD_AUDIO_FUNC_1_FORMAT_1_N_BYTES_PER_SAMPLE_TX, CFG_TUD_AUDIO_FUNC_1_N_CHANNELS_TX), /*_interval*/ 0x01),                                                                                                                                                                  /* Class-Specific AS Isochronous Audio Data Endpoint Descriptor(4.10.1.2) */ \
        TUD_AUDIO20_DESC_CS_AS_ISO_EP(/*_attr*/ AUDIO20_CS_AS_ISO_DATA_EP_ATT_NON_MAX_PACKETS_OK, /*_ctrl*/ AUDIO20_CTRL_NONE, /*_lockdelayunit*/ AUDIO20_CS_AS_ISO_DATA_EP_LOCK_DELAY_UNIT_UNDEFINED, /*_lockdelay*/ 0x0000)

#endif
