/*
 * ui_control_internal.h
 *
 *  Created on: Feb 18, 2026
 */

#ifndef UI_CONTROL_INTERNAL_H_
#define UI_CONTROL_INTERNAL_H_

#include <stdbool.h>
#include <stdint.h>

#include "stm32h7rsxx.h"
#include "stm32h7rsxx_hal_dma.h"
#include "ui_persist_internal.h"

// Ch.15のProgram Change番号。MIDI/Configurator互換値であり変更しない
// （対応表: Docs/reference/midi/receive.md）。
typedef enum
{
    UI_MIDI_PROGRAM_CH1_LINE = 0,
    UI_MIDI_PROGRAM_CH1_PHONO = 1,
    UI_MIDI_PROGRAM_CH2_LINE = 2,
    UI_MIDI_PROGRAM_CH2_PHONO = 3,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_A_CH1 = 4,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_A_CH2 = 5,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_A_USB12 = 6,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_A_USB34 = 7,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_B_CH1 = 8,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_B_CH2 = 9,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_B_USB12 = 10,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_B_USB34 = 11,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_POST_CH1 = 12,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_POST_CH2 = 13,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_POST_USB12 = 14,
    UI_MIDI_PROGRAM_CH_FADER_ASSIGN_POST_USB34 = 15,
    UI_MIDI_PROGRAM_CH1_MODE_DISABLE = 16,
    UI_MIDI_PROGRAM_CH1_MODE_DVS = 17,
    UI_MIDI_PROGRAM_CH1_MODE_SYNTH = 18,
    UI_MIDI_PROGRAM_CH2_MODE_DISABLE = 19,
    UI_MIDI_PROGRAM_CH2_MODE_DVS = 20,
    UI_MIDI_PROGRAM_CH2_MODE_SYNTH = 21,
    UI_MIDI_PROGRAM_RETURN_CH_USB12 = 22,
    UI_MIDI_PROGRAM_RETURN_CH_USB34 = 23,
    UI_MIDI_PROGRAM_RETURN_CH_NONE = 24,
    UI_MIDI_PROGRAM_HP_OUT_CH_FADER_A = 25,
    UI_MIDI_PROGRAM_HP_OUT_CH_FADER_B = 26,
    UI_MIDI_PROGRAM_HP_OUT_THRU = 27,
    UI_MIDI_PROGRAM_HP_OUT_MASTER = 28,
    UI_MIDI_PROGRAM_CH_FADER_AUX_SENSOR2_TO_A = 29,
    UI_MIDI_PROGRAM_CH_FADER_AUX_SENSOR2_TO_B = 30,
    UI_MIDI_PROGRAM_CH_FADER_AUX_SENSOR3_TO_A = 31,
    UI_MIDI_PROGRAM_CH_FADER_AUX_SENSOR3_TO_B = 32,
    UI_MIDI_PROGRAM_CH_FADER_REVERSE_A_OFF = 33,
    UI_MIDI_PROGRAM_CH_FADER_REVERSE_A_ON = 34,
    UI_MIDI_PROGRAM_CH_FADER_REVERSE_B_OFF = 35,
    UI_MIDI_PROGRAM_CH_FADER_REVERSE_B_ON = 36,
    UI_MIDI_PROGRAM_SYNTH_RATIO_OCTAVE = 37,
    UI_MIDI_PROGRAM_SYNTH_RATIO_HARMONIC = 38,
    UI_MIDI_PROGRAM_SYNTH_RATIO_CHORD = 39,
    UI_MIDI_PROGRAM_SYNTH_WARP_CLEAN = 40,
    UI_MIDI_PROGRAM_SYNTH_WARP_CROSSFOLD = 41,
    UI_MIDI_PROGRAM_SYNTH_WARP_RING_MOD = 42,
    UI_MIDI_PROGRAM_SYNTH_WARP_COMPARATOR = 43,
    UI_MIDI_PROGRAM_CURVE_EDIT_MODE_OFF = 120,
    UI_MIDI_PROGRAM_CURVE_EDIT_MODE_ON = 121,
    UI_MIDI_PROGRAM_MUX_OUTPUT_CC = 122,
    UI_MIDI_PROGRAM_MUX_OUTPUT_NOTE = 123,
    UI_MIDI_PROGRAM_ARM_UF2_BOOTLOADER = 124,
    UI_MIDI_PROGRAM_CANCEL_UF2_BOOTLOADER = 125,
    UI_MIDI_PROGRAM_REQUEST_EEPROM_DUMP = 126,
    UI_MIDI_PROGRAM_SAVE_EEPROM = 127,
} ui_control_midi_program_t;

// Runtime DSP parameter update switch for A/B diagnosis.
// 0: disable ui_control_task() DSP writes (noise root-cause test mode)
// 1: enable normal runtime control updates
#define ENABLE_DSP_RUNTIME_CONTROL 1

// persist: UI facadeがsnapshotを集約/検証/適用する。
void ui_control_get_persist_state(ui_persist_state_t* state);
bool ui_control_validate_persist_state(const ui_persist_state_t* state);
bool ui_control_apply_persist_state(const ui_persist_state_t* state);

void ui_control_reset_state(void);

#endif /* UI_CONTROL_INTERNAL_H_ */
